name: Build macOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller

    - name: Build the application
      run: |
        pyinstaller --onefile --windowed --name="ExcelCombiner" combine_app_en.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ExcelCombiner-macOS
        path: dist/ExcelCombiner.app
